CREATE DATABASE IF NOT EXISTS rsvp_master;
USE rsvp_master;

CREATE TABLE admins (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE guests (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(150) NOT NULL UNIQUE,
	phone VARCHAR(20) NOT NULL
);

CREATE TABLE rsvps (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	guest_id INT UNSIGNED NOT NULL UNIQUE,
	dietary_preference VARCHAR(100) NOT NULL,
	seat_number INT UNSIGNED NULL UNIQUE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_rsvps_guest
		FOREIGN KEY (guest_id) REFERENCES guests(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
